server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

multiplicationHost: http://localhost:8000/api/v1

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka/

spring:
  profiles: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/nrf_account
#    username: nrf_account
#    password: DBLab1004**
    username: charlie
    password: charlie123
#    sql-script-encoding: UTF-8
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:

    database: postgresql
    hibernate:
      ddl-auto: validate

    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true