server:
  port: 8761

spring:
  application:
    name: msa-architecture-eureka-server

  profiles: dev


eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 5