spring:
  profiles: dev

server:
  port: 8000

zuul:
  ignoredServices: '*'
  prefix: /api/v1
  routes:
    accounts:
      path: /accounts/**
      serviceId: account
      strip-prefix: false
    accountGroups:
      path: /accountGroups/**
      serviceId: account
      strip-prefix: false
    groups:
      path: /groups/**
      serviceId: account
      strip-prefix: false
    cncs:
      path: /cncs/**
      serviceId: cnc
      strip-prefix: false
    devices:
      path: /devices/**
      serviceId: device
      strip-prefix: false
    models:
      path: /models/**
      serviceId: model
      strip-prefix: false
    model-types:
      path: /model-types/**
      serviceId: model
      strip-prefix: false
    actuatings:
      path: /actuatings/**
      serviceId: actuating
      strip-prefix: false
    actuators:
      path: /actuators/**
      serviceId: device
      strip-prefix: false
    sensings:
      path: /sensings/**
      serviceId: sensing
      strip-prefix: false
    sensors:
      path: /sensors/**
      serviceId: device
      strip-prefix: false



hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 100000
  threadpool:
    default:
      coreSize: 1000
      maximumSize: 10000
      queueSizeRejectionThreshold: -1
      maxQueueSize: -1

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka/

