#multiplicationHost: http://192.168.10.40:8000/api/v1

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    ip-address: "localhost"
    #ip-address: "${HOST}"

spring:
  profiles: prod
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5434/nrf_cnc
    username: nrf_cnc
    password: DBLab1004**
    sql-script-encoding: UTF-8
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    database: postgresql
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

logging:
  level:
    io.wisoft.iotplatform: debug
    org.springframework.web: debug
    org.springframework: off
  file:
    name: /cnc/logs/api-server-dev.log
